In [2]:
import os
import pandas as pd
import pymysql
import numpy as np
from tqdm.auto import tqdm
import warnings
import db
warnings.filterwarnings('ignore')
from selenium import webdriver
import time
#import pyautogui
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re
import numpy as np
import requests
from lxml.html import fromstring
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException

conn = db.getConnRSTR()
cursor = conn.cursor()


def dev_db_conn(): 
    """개발 DB 접속 함수""" 
    conn = pymysql.connect( 
        host = 'db-7ma06.pub-cdb.ntruss.com', 
        user = 'redtable', 
        password = 'fpemxpdlqmf5491!@#', 
        autocommit = True, 
        cursorclass = pymysql.cursors.DictCursor) 
    return conn

def live_db_conn():
    """Live DB 접속 함수"""
    conn = pymysql.connect(
        host = "db-6j3k3.pub-cdb.ntruss.com", 
        user = "redtable",
        password = "fpemxpdlqmf5491!@#",
        autocommit = True, 
        cursorclass = pymysql.cursors.DictCursor, 
        db = "redtable2021")
    return conn

In [17]:
from bs4 import BeautifulSoup
import os
import requests
import time
import pandas as pd
from tqdm.auto import tqdm
import warnings
warnings.filterwarnings('ignore')

#url 은 네이버에 파이썬이라고 검색하고 나온 검색결과 URL 주소로 설정
url = 'https://www.mukbangmap.com/channel/ssg'

In [18]:
for i in range(14):
    i += 1
    #driver.get(f"{url}+'/'+i}")
    print(f"{url}/{i}")

https://www.mukbangmap.com/channel/ssg/1
https://www.mukbangmap.com/channel/ssg/2
https://www.mukbangmap.com/channel/ssg/3
https://www.mukbangmap.com/channel/ssg/4
https://www.mukbangmap.com/channel/ssg/5
https://www.mukbangmap.com/channel/ssg/6
https://www.mukbangmap.com/channel/ssg/7
https://www.mukbangmap.com/channel/ssg/8
https://www.mukbangmap.com/channel/ssg/9
https://www.mukbangmap.com/channel/ssg/10
https://www.mukbangmap.com/channel/ssg/11
https://www.mukbangmap.com/channel/ssg/12
https://www.mukbangmap.com/channel/ssg/13
https://www.mukbangmap.com/channel/ssg/14

### 데이터 크롤링

In [55]:
driver.quit()

In [43]:
# Selenium 웹드라이버 시작
driver = webdriver.Chrome()
time.sleep(1)
data2 = []

for i in range(154):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    date = soup_1.find('span', class_='ChannelShopContent_youtubeUpdateDate__WBZ9D').text if soup_1.find('span', class_='ChannelShopContent_youtubeUpdateDate__WBZ9D') else 'no date'

    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i])


driver.quit()

In [44]:
#체크
pd.DataFrame(data2)

,0,1,2,3,4,5,6
0,대성집,성시경의 먹을텐데 l 대성집 도가니탕,서울 종로구 행촌동,02-735-4259,도가니탕 ∙ 수육,no date,1
1,어머니대성집,성시경의 먹을텐데 l 어머니 대성집 해장국,서울 동대문구 용두동,02-923-1718,해장국 ∙ 수육,no date,2
2,디어스베이커리,성시경의 먹을텐데 l 약수 순대국,서울 중구 신당동,02-2232-1749,카레고로케 ∙ 튀긴단팥빵,no date,3
3,풍미분식,성시경의 먹을텐데 l 약수 순대국,서울 중구 신당동,,찹쌀도너츠,no date,4
4,약수순대,성시경의 먹을텐데 l 약수 순대국,서울 중구 신당동,02-2236-5926,순대국 ∙ 머리고기,no date,5
...,...,...,...,...,...,...,...
149,전원식당,장치도 훌륭한 두루치기 맛집!,강원 속초시 동명동,010-5505-4881,두루치기,∙2024.5.22. 영상 업로드,150
150,효제루,볶음 탕수육이 훌륭한 중국집!,서울 종로구 효제동,02-6448-0772,탕수육 ∙ 팔보채 ∙ 해물짬뽕 ∙ 짜장면 ∙ 새우볶음밥,∙2024.5.29. 영상 업로드,151
151,풍성감자탕,맑고 깨끗한 맛의 우거지 감자탕!,서울 광진구 구의동,02-446-0354,감자탕,∙2024.6.10. 영상 업로드,152
152,막동이회관,정말 맛있다! 정말 맛있는 고기집!,광주 동구 소태동,062-222-0840,생고기 ∙ 안심추리 ∙ 차돌박이 ∙ 갈비살 ∙ 살치살 ∙ 토시살 ∙ 곰탕 ∙ 돌솥비...,∙2024.6.17. 영상 업로드,153
153,,,,,,no date,154

In [ ]:
# 풍자 

url = 'https://www.mukbangmap.com/channel/poongja'

driver = webdriver.Chrome()
time.sleep(1)

for i in range(187):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    date = soup_1.find('span', class_='ChannelShopContent_youtubeUpdateDate__WBZ9D').text if soup_1.find('span', class_='ChannelShopContent_youtubeUpdateDate__WBZ9D') else 'no date'
    print(data2)
    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i])


driver.quit()

In [56]:
# 백종원 
url = 'https://www.mukbangmap.com/channel/bjw'

driver = webdriver.Chrome()
time.sleep(1)

for i in range(85):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    date = soup_1.find('span', class_='ChannelShopContent_youtubeUpdateDate__WBZ9D').text if soup_1.find('span', class_='ChannelShopContent_youtubeUpdateDate__WBZ9D') else 'no date'
    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i, "백종원"])


driver.quit()

In [57]:
# 최자로드

url = 'https://www.mukbangmap.com/channel/cjroad/'

driver = webdriver.Chrome()
time.sleep(1)

for i in range(117):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i, "최자"])


driver.quit()

In [62]:
# 현주엽

url = 'https://www.mukbangmap.com/channel/hjy/'

driver = webdriver.Chrome()
time.sleep(1)

for i in range(130,200):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i, "현주"])


driver.quit()

In [65]:
pd.DataFrame(data2)

,0,1,2,3,4,5,6,7
0,청보석,전남 곡성의 석곡시장 근처의 찐한 콩국수집! 김치까지 쫙~,전남 곡성군 석곡면,061-363-4664,콩국수,no date,1,백종원
1,시장닭발,50년된 불맛 제대로 연탄 닭구이집! 막걸리 한잔 캬~,경북 군위군 군위읍,054-382-2128,연탄 닭구이(닭발+닭목+닭포) ∙ 고등어 구이 ∙ 닭개장,no date,2,백종원
2,청도가마솥국밥,육회비빔밥으로 유명한 국밥집! 국밥은 없습니데이~,경북 청도군 청도읍,054-371-0222,육회비빔밥 ∙ 뭉튀기,no date,3,백종원
3,토종마을,말도 안되는 저렴한 가격의 정성 가득 국밥집,충북 음성군 감곡면,043-881-9611,국밥 ∙ 수육(+흑임자편육+닭발),no date,4,백종원
4,진량돼지찌개,"""라면사리에 밥 비벼 먹고, 한잔까지 해결하는 찌개""",경북 경산시 진량읍,053-857-6071,돼지찌개,no date,5,백종원
...,...,...,...,...,...,...,...,...
474,운멜로,행리단길의 핫플레이스!,경기 수원시 신풍동,031-256-0149,빼쉐 파스타 ∙ 풍기크레마 리조또,∙2024.4.25. 영상 업로드,73,홍석천
475,요미우돈교자,비주얼과 맛까지 훌륭한 행리단길 맛집!,경기 수원시 신풍동,0507-1426-8113,넓적우동 ∙ 붓카케 우동 ∙ 고기 교자 만두 ∙ 가지 불고기 덮밥,∙2024.4.25. 영상 업로드,74,홍석천
476,원조부산아구,홍석천 강력 추천 맛집!,서울 강남구 논현동,02-546-9947,꽃게+아구 범벅 ∙ 꽃게찜 ∙ 간장게장 ∙ 주먹김밥,∙2024.4.25. 영상 업로드,75,홍석천
477,온도계,숯불에 구워 먹는 닭갈비 맛집!,서울 강동구 성내동,0507-1405-7469,마늘소금닭갈비 ∙ 간장양념닭갈비 ∙ 매운양념닭갈비,∙2024.4.25. 영상 업로드,76,홍석천
478,,,,,,∙2024.4.25. 영상 업로드,77,홍석천

In [64]:
# 홍석천

url = 'https://www.mukbangmap.com/channel/hsclwi/'

driver = webdriver.Chrome()
time.sleep(1)

for i in range(77):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i, "홍석천"])


driver.quit()

In [66]:
# 오사카사는사람

url = 'https://www.mukbangmap.com/channel/osasa'

driver = webdriver.Chrome()
time.sleep(1)

for i in range(97):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i, "오사카"])


driver.quit()

In [67]:
#고독한한식미식가

url = 'https://www.mukbangmap.com/channel/goro/'

driver = webdriver.Chrome()
time.sleep(1)

for i in range(143):
    i += 1
    driver.get(f"{url}/{i}")
    #html_content = requests.get(f"{url}/{i}").text
    #soup = BeautifulSoup(html_content, 'html.parser')
    time.sleep(2)
    html_content = driver.page_source
    soup_1 = BeautifulSoup(html_content, 'html.parser')

    shop_name = soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI').text if soup_1.find('span', class_='ChannelShopContent_shopNameText__MEVSI') else ''
    contents = soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na').text if soup_1.find('p', class_='ChannelShopContent_shopDesc__oU6Na') else ''
    address = soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl').text if soup_1.find('span', class_='ChannelShopContent_shopAddress__3tYSl') else ''
    phone = soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM').text if soup_1.find('a', class_='ChannelShopContent_shopTelLink__lgGGM') else ''
    menu = soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt').text if soup_1.find('p', class_='ChannelShopContent_shopMenuText__Ey4Gt') else ''
    # 데이터를 리스트에 추가
    data2.append([shop_name, contents, address, phone, menu, date, i, "고독한한식"])


driver.quit()

In [68]:
final = pd.DataFrame(data2)
#final.to_excel("백종원~고독한.xlsx")

In [35]:
df = final.copy()

대성집
서울 종로구 행촌동
02-735-4259
도가니탕 ∙ 수육
no date

## 데이터처리

In [80]:
# df
import open_api2

AREA1, AREA2, AREA3, JIBUN, DORO, LAT, LON, POSTCODE = ([] for _ in range(8))

area1 = []
for idx,row in df.iterrows():
    address_text = row["주소"]
    try :
        standard_text = open_api2.preprocess(address_text)
        AREA1.append(standard_text[0])
        AREA2.append(standard_text[1])
        AREA3.append(standard_text[2])
        JIBUN.append(standard_text[3])
        DORO.append(standard_text[4])
        LAT.append(standard_text[5])
        LON.append(standard_text[6])
        #.append(standard_text[4])
        
    except:
        AREA1.append("")
        AREA2.append("")
        AREA3.append("")
        JIBUN.append("")
        DORO.append("")
        LAT.append("")
        LON.append("")

df["address_jibun"] = JIBUN
df["address_road"] = DORO
df["latitude"] = LAT
df["longitude"] = LON
df["AREA1"] = AREA1
df["AREA2"] = AREA2
df["AREA3"] = AREA3

In [207]:
pd.reset_option('display.max_rows')

In [208]:
df

,Unnamed: 0,상점명,content,주소,전화번호,메인메뉴,방송날짜,방송회차,프로그램명,address_jibun,address_road,latitude,longitude,AREA1,AREA2,AREA3
0,0,청보석,전남 곡성의 석곡시장 근처의 찐한 콩국수집! 김치까지 쫙~,전남 곡성군 석곡면,061-363-4664,콩국수,no date,1,님아 그 시장을 가오,전라남도 곡성군 석곡면,None,35.1329306334763,127.25410906693,전라남도,곡성군,석곡면
1,1,시장닭발,50년된 불맛 제대로 연탄 닭구이집! 막걸리 한잔 캬~,경북 군위군 군위읍,054-382-2128,연탄 닭구이(닭발+닭목+닭포) ∙ 고등어 구이 ∙ 닭개장,no date,2,님아 그 시장을 가오,대구광역시 군위군 군위읍,None,36.2398089970225,128.568752594251,대구광역시,군위군,군위읍
2,2,청도가마솥국밥,육회비빔밥으로 유명한 국밥집! 국밥은 없습니데이~,경북 청도군 청도읍,054-371-0222,육회비빔밥 ∙ 뭉튀기,no date,3,님아 그 시장을 가오,경상북도 청도군 청도읍,None,35.6507107731232,128.743825152022,경상북도,청도군,청도읍
3,3,토종마을,말도 안되는 저렴한 가격의 정성 가득 국밥집,충북 음성군 감곡면,043-881-9611,국밥 ∙ 수육(+흑임자편육+닭발),no date,4,님아 그 시장을 가오,충청북도 음성군 감곡면,None,37.1123604145514,127.643552339827,충청북도,음성군,감곡면
4,4,진량돼지찌개,"""라면사리에 밥 비벼 먹고, 한잔까지 해결하는 찌개""",경북 경산시 진량읍,053-857-6071,돼지찌개,no date,5,님아 그 시장을 가오,경상북도 경산시 진량읍,None,35.8739232681781,128.816219686495,경상북도,경산시,진량읍
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,1050,우성닭갈비,양념이 골고루 맛있는 닭갈비! 치즈사리는 개취!,강원 춘천시 퇴계동,033-242-3833,닭갈비 ∙ 치즈사리 ∙ 우동사리 ∙ 막국수,∙2024.6.7. 영상 업로드,182,또간집,강원특별자치도 춘천시 퇴계동,None,37.864489878017,127.726200566679,강원특별자치도,춘천시,퇴계동
1051,1051,학곡리막국수닭갈비,육수에 졸여 먹는 찐한 닭갈비 맛집,강원 춘천시 석사동,033-261-5775,닭갈비 ∙ 닭내장 ∙ 볶음밥,∙2024.6.7. 영상 업로드,183,또간집,강원특별자치도 춘천시 석사동,None,37.8552732879352,127.746663141751,강원특별자치도,춘천시,석사동
1052,1052,강촌마을,영등포 40년 현지인의 추천 밥집!,서울 영등포구 영등포동6가,02-2633-0779,돌솥영양밥,∙2024.6.21. 영상 업로드,184,또간집,서울특별시 영등포구 영등포동6가,None,37.5215905083397,126.90316740849,서울특별시,영등포구,영등포동6가
1053,1053,감나무집,영등포 직장인들의 찐맛집,서울 영등포구 영등포동8가,0507-1316-3556,오삼불고기정식 ∙ 돼지갈비,∙2024.6.21. 영상 업로드,185,또간집,서울특별시 영등포구 영등포동8가,None,37.5283028633871,126.905253942411,서울특별시,영등포구,영등포동8가
1054,1054,태양생고기,영등포 현지인 맛집! 야채는 사이드에서 같이 구워 먹기!,서울 영등포구 영등포동8가,02-2637-8268,가브리살,∙2024.6.21. 영상 업로드,186,또간집,서울특별시 영등포구 영등포동8가,None,37.5283028633871,126.905253942411,서울특별시,영등포구,영등포동8가

### rstr_id 매핑
1. rstr id 연결 - 인허가번호랑 rstr 번호 가져오기
2. 업로드

In [74]:
with dev_db_conn() as conn:
    cur = conn.cursor()
    sql = """
    SELECT r.ID, r.BSNS_LCNC_NO, r.SOURCE_ID, r.FOODSAFETY_ID_NEW, r.SOURCE, r.RSTR_NM , r.AREA_NM_1, r.AREA_NM_2, r.AREA_NM_3, r.RSTR_RDNMADR, r.RSTR_LNNO_ADRES
    FROM redtable01.RSTR r;"""
    cur.execute(sql)
    rstr = pd.DataFrame(cur.fetchall())
rstr

,ID,BSNS_LCNC_NO,SOURCE_ID,FOODSAFETY_ID_NEW,SOURCE,RSTR_NM,AREA_NM_1,AREA_NM_2,AREA_NM_3,RSTR_RDNMADR,RSTR_LNNO_ADRES
0,1,None,11559726.0,NaN,naver,예술식당,광주광역시,동구,학동,광주광역시 동구 남문로753번길 9,광주광역시 동구 학동 633-12
1,2,None,11580073.0,NaN,naver,전통뚝배기생태한마리,광주광역시,동구,산수동,광주광역시 동구 필문대로191번길 15-2,광주광역시 동구 산수동 517-23
2,3,None,11625001.0,NaN,naver,피자헛,광주광역시,동구,금남로5가,광주광역시 동구 금남로 172-1,광주광역시 동구 금남로5가 114-3
3,4,None,11710448.0,NaN,naver,춘하추동,광주광역시,동구,지산2동,광주광역시 동구 지호로 151,광주광역시 동구 지산2동 71
4,5,None,11721084.0,NaN,naver,금성산장,광주광역시,동구,운림동,None,광주광역시 동구 운림동 88-1
...,...,...,...,...,...,...,...,...,...,...,...
1697006,300680039,naver_1913180910,NaN,0.0,naver,헤이미쉬,경기도,성남시,중원구,경기도 성남시 중원구 도촌남로 22,경기도 성남시 중원구 도촌동 700
1697007,300680040,naver_1979890842,NaN,0.0,naver,명선생마사지 정체원,서울특별시,성동구,성수동1가,서울특별시 성동구 상원길 63,서울특별시 성동구 성수동1가 706
1697008,300680041,naver_12237442,NaN,NaN,None,한국건강관리협회 건강증진의원 부산동래,부산광역시,동래구,온천동,부산광역시 동래구 충렬대로 145,부산광역시 동래구 온천동 1438-2
1697009,300680042,namane_381,381.0,NaN,namane,CU 용인행정타운점,경기도,용인시,처인구,경기도 용인시 처인구 중부대로 1154,경기도 용인시 처인구 삼가동 250-39
1697010,300680043,20240045800,NaN,NaN,None,한식 왕비집,서울특별시,중구,명동2가,서울특별시 중구 명동6길 15,서울특별시 중구 명동2가 52-5

In [209]:
merge1 = pd.merge(df,rstr,left_on=['상점명','AREA2'],right_on=['RSTR_NM','AREA_NM_2'],how='left')
merge1.drop_duplicates(subset=['ID','상점명','BSNS_LCNC_NO'],inplace=True)
merge1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1166 entries, 0 to 1191
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1166 non-null   int64
 1   상점명                1166 non-null   object
 2   content            947 non-null    object
 3   주소                 1166 non-null   object
 4   전화번호               821 non-null    object
 5   메인메뉴               1166 non-null   object
 6   방송날짜               1166 non-null   object
 7   방송회차               1166 non-null   int64
 8   프로그램명              1166 non-null   object
 9   address_jibun      1166 non-null   object
 10  address_road       335 non-null    object
 11  latitude           835 non-null    object
 12  longitude          835 non-null    object
 13  AREA1              835 non-null    object
 14  AREA2              835 non-null    object
 15  AREA3              835 non-null    object
 16  ID                 645 non-null    float64
 17  BSNS_LCNC_NO       645 non-null    object
 18  SOURCE_ID          584 non-null    float64
 19  FOODSAFETY_ID_NEW  637 non-null    float64
 20  SOURCE             645 non-null    object
 21  RSTR_NM            645 non-null    object
 22  AREA_NM_1          644 non-null    object
 23  AREA_NM_2          644 non-null    object
 24  AREA_NM_3          644 non-null    object
 25  RSTR_RDNMADR       644 non-null    object
 26  RSTR_LNNO_ADRES    644 non-null    object
dtypes: float64(3), int64(2), object(22)
memory usage: 255.1+ KB

In [210]:
drop = merge1['ID'].value_counts()
# 빈도가 2 이상인 ID를 추출
ids_to_keep = drop[drop >= 2].index

# merge1 데이터프레임에서 해당 ID를 가진 행만 필터링
filtered_merge1 = merge1[merge1['ID'].isin(ids_to_keep)]
filtered_merge1.sort_values(by='상점명')

Empty DataFrame
Columns: [Unnamed: 0, 상점명, content, 주소, 전화번호, 메인메뉴, 방송날짜, 방송회차, 프로그램명, address_jibun, address_road, latitude, longitude, AREA1, AREA2, AREA3, ID, BSNS_LCNC_NO, SOURCE_ID, FOODSAFETY_ID_NEW, SOURCE, RSTR_NM, AREA_NM_1, AREA_NM_2, AREA_NM_3, RSTR_RDNMADR, RSTR_LNNO_ADRES]
Index: []

[0 rows x 27 columns]

In [217]:
#체크
merge1[['상점명','ID','주소','AREA2']].sample(20)

                     상점명        ID            주소 AREA2
1075         경춘자의 라면땡기는날       NaN     서울 종로구 화동   종로구
1111               삼오불고기   11569.0    부산 수영구 광안동   수영구
619                 후게츠칸       NaN       일본 오사카   None
744           야키니쿠 라멘 밋짱       NaN          일본    None
941                오쁘띠베르       NaN    서울 종로구 통인동   종로구
40                도산식육식당    6269.0    경북 구미시 지산동   구미시
613                  동아리  392093.0      서울 중구 정동    중구
992                 성수부두  749155.0  서울 성동구 성수동2가   성동구
627              阿波半田製麺所       NaN       일본 오사카   None
443                  전주집  803405.0    서울 강서구 방화동   강서구
384                  무수옥   53167.0    서울 도봉구 도봉동   도봉구
54    Polo Fried Chicken       NaN        태국 방콕   None
46                 달동네식당       NaN    경남 함양군 함양읍   함양군
212                  은주정   28409.0     서울 중구 주교동    중구
932             안동집 손칼국시       NaN   서울 동대문구 제기동  동대문구
936                 야스노야  621088.0    서울 용산구 후암동   용산구
263                케이하우스       NaN    서울 강남구 청담동   강남구
574               무기토 토리       NaN       일본 오사카   None
707   YO-HO's cafe Lanai       NaN          일본    None
502               홍두깨칼국수  370155.0     서울 중구 황학동    중구

In [218]:
merge2 = merge1[merge1['ID'].isnull()]

In [220]:
## 매칭안된 500개에 대해 전화번호로 연결

with dev_db_conn() as conn:
    cursor = conn.cursor()
    sql = f"""
SELECT T3.SRC_ID AS 'store_id', T1.id AS 'naver_id', T2.RSTR_ID, CONCAT('naver_', T1.id) AS 'business_7', T4.AREA_NM_2
FROM redtable_raw_2022.naver_restaurant T1
INNER JOIN redtable01.RSTR_CONN T2 ON T1.id = T2.SRC_ID
INNER JOIN redtable01.RSTR_CONN T3 ON T2.RSTR_ID = T3.RSTR_ID
inner join redtable01.RSTR T4 ON T4.ID = T3.RSTR_ID
WHERE T2.SRC = 'naver' AND T3.SRC = 'live_db';
    """
    cursor.execute(sql)
    store_rstr = cursor.fetchall()
store_rstr = pd.DataFrame(store_rstr)
store_rstr

        store_id    naver_id    RSTR_ID        business_7 AREA_NM_2
0         199172    16664019       1086    naver_16664019       강서구
1         129954  1117106356       1088  naver_1117106356       종로구
2         786516  1845996048       1094  naver_1845996048       사상구
3         287609    11782628       1096    naver_11782628       태백시
4         199137  1456094039       1099  naver_1456094039      None
...          ...         ...        ...               ...       ...
561069   1190584  1368334876  300229974  naver_1368334876       강동구
561070   1190588  1555808990  300229978  naver_1555808990       삼척시
561071   1190734  1290988160  300230130  naver_1290988160       철원군
561072   1190779  1146939043  300230176  naver_1146939043       강진군
561073   1190793  1234493232  300230190  naver_1234493232       구미시

[561074 rows x 5 columns]

In [125]:
## 매칭안된 500개에 대해 전화번호로 연결

with live_db_conn() as conn:
    cursor = conn.cursor()
    sql = f"""
SELECT s.id , s.telephone , s.telephone_plain, s.name
FROM redtable2021.store s;
    """
    cursor.execute(sql)
    store = cursor.fetchall()
store = pd.DataFrame(store)
store

              id       telephone telephone_plain                      name
0          10001     02-111-1111       021111111                   테스트 매장2
1          10002   070-1234-1234     07012341234                    테스트 매장
2          10003     02-756-3449       027563449                    테스트 매장
3          10004      0269647955      0269647955                  REDTABLE
4          10005     02-337-9019       023379019                 삼호복집 test
...          ...             ...             ...                       ...
1619436  1631449    02-6964-7955      0269647955         KOREA TRAVEL CARD
1619437  1631450    064-740-7775      0647407775              파라다이스제주카지노지점
1619438  1631451            None            None  [창경궁] 광장시장+ 창경궁 야간 워킹 투어
1619439  1631452     02-777-7004       027777004                    한식 왕비집
1619440  1631453  0507-1376-4691    050713764691                    순수에스테틱

[1619441 rows x 4 columns]

In [222]:
refer1 = pd.merge(store_rstr,store,left_on='store_id',right_on='id',how='inner')

In [223]:
merge2.head(1)
merge2 = merge2.dropna(how='all', axis=1)

In [225]:
merge3 = pd.merge(merge2,refer1,left_on=['전화번호','AREA2'],right_on=['telephone','AREA_NM_2'],how='inner')
merge3

#이름으로 푸지우지 ㄱ

,Unnamed: 0,상점명,content,주소,전화번호,메인메뉴,방송날짜,방송회차,프로그램명,address_jibun,...,AREA3,store_id,naver_id,RSTR_ID,business_7,AREA_NM_2,id,telephone,telephone_plain,name
0,15,고향보리밥집,현지인들이 즐겨찾는 쌉밥 맛집,강원 원주시 흥업면,033-763-7959,쌈밥정식,no date,16,님아 그 시장을 가오,강원특별자치도 원주시 흥업면,...,흥업면,30396,15269100,79048,naver_15269100,원주시,30396,033-763-7959,0337637959,고향보리밥
1,22,한아름식당,대를 이어 운영하는 한우 생고기집,전남 해남군 마산면,061-533-7774,생고기 ∙ 소고기 구이,no date,23,님아 그 시장을 가오,전라남도 해남군 마산면,...,마산면,194668,12975878,37278,naver_12975878,해남군,194668,061-533-7774,0615337774,한아름
2,23,단기다루,모든게 셀프인 딤섬 뷔페!,홍콩,NaN,딤섬 뷔페,no date,24,님아 그 시장을 가오,홍콩,...,None,351137,19286604,6386,naver_19286604,None,351137,None,None,모현다방
3,23,단기다루,모든게 셀프인 딤섬 뷔페!,홍콩,NaN,딤섬 뷔페,no date,24,님아 그 시장을 가오,홍콩,...,None,910924,38443866,32957,naver_38443866,None,910924,None,None,맛나분식
4,23,단기다루,모든게 셀프인 딤섬 뷔페!,홍콩,NaN,딤섬 뷔페,no date,24,님아 그 시장을 가오,홍콩,...,None,200974,33896635,38532,naver_33896635,None,200974,None,None,옛집식당
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91638,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,명동1가,651255,1997046589,2204477,naver_1997046589,중구,651255,None,None,투썸플레이스
91639,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,명동1가,933482,1998910612,685296,naver_1998910612,중구,933482,None,None,띵크커피
91640,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,명동1가,937339,1976671861,949508,naver_1976671861,중구,937339,None,None,행복푸드
91641,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,명동1가,1055655,1916357421,300118960,naver_1916357421,중구,1055655,None,None,육냉육칼 매운떡볶이매니아
91642,1037,아리조나막창,생으로 구워먹는 고소한 대구 막창,대구 수성구 두산동,053-782-9323,생막창,∙2024.4.12. 영상 업로드,169,또간집,대구광역시 수성구 두산동,...,두산동,559312,11731271,504816,naver_11731271,수성구,559312,053-782-9323,0537829323,대구아리조나막창수성못본점

In [226]:
# 매칭후 정확도를 위해 유사성 계산 진행

from fuzzywuzzy import fuzz

def address_match_ratio(address1, address2):
    if pd.notna(address1) and pd.notna(address2):  # NaN이 아닌 경우에만 처리
        return fuzz.partial_ratio(address1, address2)
    else:
        return 0
    
# 두 열 간의 값 비교 및 유사성 계산
merge3['similarity_ratio'] = merge3.apply(lambda row: address_match_ratio(row['상점명'], row['name']), axis=1)
merge3

,Unnamed: 0,상점명,content,주소,전화번호,메인메뉴,방송날짜,방송회차,프로그램명,address_jibun,...,store_id,naver_id,RSTR_ID,business_7,AREA_NM_2,id,telephone,telephone_plain,name,similarity_ratio
0,15,고향보리밥집,현지인들이 즐겨찾는 쌉밥 맛집,강원 원주시 흥업면,033-763-7959,쌈밥정식,no date,16,님아 그 시장을 가오,강원특별자치도 원주시 흥업면,...,30396,15269100,79048,naver_15269100,원주시,30396,033-763-7959,0337637959,고향보리밥,100
1,22,한아름식당,대를 이어 운영하는 한우 생고기집,전남 해남군 마산면,061-533-7774,생고기 ∙ 소고기 구이,no date,23,님아 그 시장을 가오,전라남도 해남군 마산면,...,194668,12975878,37278,naver_12975878,해남군,194668,061-533-7774,0615337774,한아름,100
2,23,단기다루,모든게 셀프인 딤섬 뷔페!,홍콩,NaN,딤섬 뷔페,no date,24,님아 그 시장을 가오,홍콩,...,351137,19286604,6386,naver_19286604,None,351137,None,None,모현다방,25
3,23,단기다루,모든게 셀프인 딤섬 뷔페!,홍콩,NaN,딤섬 뷔페,no date,24,님아 그 시장을 가오,홍콩,...,910924,38443866,32957,naver_38443866,None,910924,None,None,맛나분식,0
4,23,단기다루,모든게 셀프인 딤섬 뷔페!,홍콩,NaN,딤섬 뷔페,no date,24,님아 그 시장을 가오,홍콩,...,200974,33896635,38532,naver_33896635,None,200974,None,None,옛집식당,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91638,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,651255,1997046589,2204477,naver_1997046589,중구,651255,None,None,투썸플레이스,17
91639,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,933482,1998910612,685296,naver_1998910612,중구,933482,None,None,띵크커피,0
91640,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,937339,1976671861,949508,naver_1976671861,중구,937339,None,None,행복푸드,0
91641,1035,신세계떡볶이,45년 전통! 마늘 풍미 가득! 부산 스타일 떡볶이 맛집!,서울 중구 명동1가,NaN,떡볶이,∙2024.3.29 영상 업로드,167,또간집,서울특별시 중구 명동1가,...,1055655,1916357421,300118960,naver_1916357421,중구,1055655,None,None,육냉육칼 매운떡볶이매니아,50
91642,1037,아리조나막창,생으로 구워먹는 고소한 대구 막창,대구 수성구 두산동,053-782-9323,생막창,∙2024.4.12. 영상 업로드,169,또간집,대구광역시 수성구 두산동,...,559312,11731271,504816,naver_11731271,수성구,559312,053-782-9323,0537829323,대구아리조나막창수성못본점,100

In [280]:
merge4 = merge3[merge3['similarity_ratio'] >= 80]
merge4 = merge4[merge4['AREA_NM_2'].notnull()]
merge4

,Unnamed: 0,상점명,content,주소,전화번호,메인메뉴,방송날짜,방송회차,프로그램명,address_jibun,...,store_id,naver_id,RSTR_ID,business_7,AREA_NM_2,id,telephone,telephone_plain,name,similarity_ratio
0,15,고향보리밥집,현지인들이 즐겨찾는 쌉밥 맛집,강원 원주시 흥업면,033-763-7959,쌈밥정식,no date,16,님아 그 시장을 가오,강원특별자치도 원주시 흥업면,...,30396,15269100,79048,naver_15269100,원주시,30396,033-763-7959,0337637959,고향보리밥,100
1,22,한아름식당,대를 이어 운영하는 한우 생고기집,전남 해남군 마산면,061-533-7774,생고기 ∙ 소고기 구이,no date,23,님아 그 시장을 가오,전라남도 해남군 마산면,...,194668,12975878,37278,naver_12975878,해남군,194668,061-533-7774,0615337774,한아름,100
8541,79,맥시칸치킨하우스,유린기 스타일 야채통닭과 옛날 치킨!,울산 동구 동부동,052-233-1657,고추야채통닭 ∙ 양념반후라이드반치킨,∙2024.3.28. 영상 업로드,80,님아 그 시장을 가오,울산광역시 동구 동부동,...,911047,1740841946,26277,naver_1740841946,동구,911047,052-233-1657,0522331657,치킨하우스,100
9638,96,옥경이네건생선,숙성된 반건조 생선의 참맛!,서울 중구 황학동,02-2233-3494,반건조 민어찜 ∙ 갑오징어 구이 ∙ 딱돔 구이,∙2024.4.25. 영상 업로드,12,최자로드,서울특별시 중구 황학동,...,43893,1960119730,457817,naver_1960119730,중구,43893,02-2233-3494,0223333494,옥경이네 건생선,86
9639,118,순금이떡볶이,식어도 맛있는 떡볶이와 어묵!,서울 광진구 구의동,02-455-8090,떡볶이,∙2024.4.25. 영상 업로드,34,최자로드,서울특별시 광진구 구의동,...,763007,31747148,25041,naver_31747148,광진구,763007,02-455-8090,024558090,순금이떡볶이,100
9640,137,우정양곱창,신선하고 깨끗한 양곱창 맛집,서울 강남구 논현동,02-6083-5830,모듬 곱창 ∙ 특양구이,∙2024.4.25. 영상 업로드,53,최자로드,서울특별시 강남구 논현동,...,123728,1921750340,648432,naver_1921750340,강남구,123728,02-6083-5830,0260835830,우정 양곱창,80
9641,138,대화정 진짜해장국,진짜 제대로된 해장국!,서울 중구 을지로6가,02-2267-8484,진짜해장국,∙2024.4.25. 영상 업로드,54,최자로드,서울특별시 중구 을지로6가,...,43237,19412363,185754,naver_19412363,중구,43237,02-2267-8484,0226788484,진짜해장국,100
9643,160,문배동육칼,이미 유명한! 얼큰한 육개장 칼국수!,서울 용산구 문배동,02-713-6204,육칼(육개장 칼국수),∙2024.4.25. 영상 업로드,76,최자로드,서울특별시 용산구 문배동,...,120897,11717878,309027,naver_11717878,용산구,120897,02-713-6204,027136204,문배동 육칼,80
9645,184,곰막식당,신선한 제주의 맛 총집합!,제주 제주시 구좌읍,064-727-5111,고등어회 ∙ 한치회 ∙ 회국수 ∙ 성게국수,∙2024.4.25. 영상 업로드,100,최자로드,제주특별자치도 제주시 구좌읍,...,267161,31204698,422172,naver_31204698,제주시,267161,064-727-5111,0647275111,곰막,100
9845,265,유어다이닝,NaN,서울 마포구 망원동,070-7585-0412,이탈리안(파스타 ∙ 라자냐 ∙ 까넬로니 등),∙2024.4.25. 영상 업로드,65,먹보스쭈엽이,서울특별시 마포구 망원동,...,124932,1628461261,867112,naver_1628461261,마포구,124932,070-7585-0412,07075850412,유어 다이닝,80
9846,287,언양기와집불고기,NaN,울산 울주군 언양읍,052-262-4884,언양불고기,∙2024.4.25. 영상 업로드,87,먹보스쭈엽이,울산광역시 울주군 언양읍,...,11530,11717646,23349,naver_11717646,울주군,11530,052-262-4884,0522624884,기와집,100
9847,302,조박집,NaN,서울 마포구 용강동,02-718-4410,양념돼지갈비 ∙ 동치미국수,∙2024.4.25. 영상 업로드,102,먹보스쭈엽이,서울특별시 마포구 용강동,...,14818,1038687910,187278,naver_1038687910,마포구,14818,02-718-4410,027184410,조박집투,100
9848,314,대청마루I,가성비 좋은 냉동삼겹살 맛집,서울 중구 필동2가,02-2285-2650,냉동삼겹살 ∙ 돼지고기구이 ∙ 볶음밥,∙2024.4.25. 영상 업로드,114,먹보스쭈엽이,서울특별시 중구 필동2가,...,648448,13154988,123891,naver_13154988,중구,648448,02-2285-2650,0222852650,대청마루,100
14507,383,바로쿡치킨,삼겹살 구우며 즐기는 치킨 맛집!,경기 광주시 도척면,031-763-8593,삼겹살 ∙ 순살프라이드치킨 ∙ 제육덮밥 ∙ 오징어덮밥 ∙ 청국장 ∙ 황도,∙2024.4.25. 영상 업로드,183,먹보스쭈엽이,경기도 광주시 도척면,...,335640,459743984,564870,naver_459743984,광주시,335640,031-763-8593,0317638593,바로쿡치킨&한우주산지,100
15698,423,오는정쪽갈비,길가다 들린 쪽갈비 맛집!,서울 종로구 체부동,02-735-5718,쪽갈비,∙2024.4.25. 영상 업로드,24,홍석천이원일,서울특별시 종로구 체부동,...,35440,36898429,645095,naver_36898429,종로구,35440,02-735-5718,027355718,오는정쪽갈비,100
80911,770,서대문 양꼬치,성시경의 먹을텐데 l 연남동 서대문 양꼬치,서울 마포구 연남동,02-6085-5888,돼지쪽갈비 ∙ 양고기전골 ∙ 양고기파볶음,no date,55,먹을텐데,서울특별시 마포구 연남동,...,100737,1882480351,425689,naver_1882480351,마포구,100737,02-6085-5888,0260855888,서대문양꼬치바,86
83927,791,진미평양냉면,성시경이 아끼는 평양냉면과 어복쟁반 집,서울 강남구 논현동,02-515-3469,제육 ∙ 만두 ∙ 어복쟁반 ∙ 물냉면,no date,76,먹을텐데,서울특별시 강남구 논현동,...,52972,37912785,34072,naver_37912785,강남구,52972,02-515-3469,025153469,진미 평양냉면,83
84750,810,옛날 칼국수,깨끗하고 맑은 칼국수와 쫀득한 수제비1,서울 노원구 상계동,02-939-6169,칼국수 ∙ 얼큰수제비 ∙ 청양 부추전 ∙ 왕만두,no date,95,먹을텐데,서울특별시 노원구 상계동,...,66370,18030542,109898,naver_18030542,노원구,66370,02-939-6169,029396169,옛날칼국수,80
85598,827,월드양념통닭,촉촉한 똥집튀김과 진짜 맛있는 치킨!,부산 사하구 장림동,051-261-9746,똥집 ∙ 반반치킨,no date,112,먹을텐데,부산광역시 사하구 장림동,...,205970,16662018,34566,naver_16662018,사하구,205970,051-261-9746,0512619746,월드 양념통닭,83
85599,828,별미순대국,순대가 기가 막힌 순대국집!,경기 의정부시 의정부동,031-838-1256,고기와순대 ∙ 순대국,no date,113,먹을텐데,경기도 의정부시 의정부동,...,395201,1377951609,683846,naver_1377951609,의정부시,395201,031-838-1256,0318381256,수제 별미순대국,100
85600,832,묵호회집,최자가 추천하는 오마카세 횟집!,서울 중구 북창동,02-779-4705,오마카세,no date,117,먹을텐데,서울특별시 중구 북창동,...,44842,18020407,12838,naver_18020407,중구,44842,02-779-4705,027794705,묵호,100
85601,835,로코스비비큐,이미 유명한 미국식 바베큐 플래서 맛집!,서울 용산구 이태원동,02-794-3234,바베큐폭립하프앤하프플래터(오리지널소스+코리안스파이시) ∙ 비프숏립(우대갈비)플래터 ...,no date,120,먹을텐데,서울특별시 용산구 이태원동,...,122449,35678401,458142,naver_35678401,용산구,122449,02-794-3234,027943234,로코스 비비큐,83
87664,893,소금집델리,NaN,서울 마포구 망원동,02-336-2617,샌드위치(잠봉뵈르) ∙ 루벤,∙2022.7.15. 영상 업로드,25,또간집,서울특별시 마포구 망원동,...,119026,1956949040,689318,naver_1956949040,마포구,119026,02-336-2617,023362617,소금집델리,100
87665,895,망원동칼짬뽕,NaN,서울 마포구 망원동,02-332-4469,홍합칼짬뽕(맵게),∙2022.7.15. 영상 업로드,27,또간집,서울특별시 마포구 망원동,...,119430,1487520652,694697,naver_1487520652,마포구,119430,02-332-4469,023324469,망원동 칼짬뽕,83
87666,896,여원찜갈비,NaN,대구 북구 검단동,053-383-1127,돼지 찜갈비(feat.볶음밥),∙2022.7.29. 영상 업로드,28,또간집,대구광역시 북구 검단동,...,528533,16059877,128158,naver_16059877,북구,528533,053-383-1127,0533831127,여원갈비식당,80
87667,905,떡도리탕,풍자의 또갈집!,서울 강남구 역삼동,02-501-2940,떡도리탕,∙2022.8.26. 영상 업로드,37,또간집,서울특별시 강남구 역삼동,...,59869,34461836,126205,naver_34461836,강남구,59869,02-501-2940,025012940,떡도리탕,100
87668,915,산울림1992,NaN,서울 마포구 창전동,02-334-0118,치즈감자전 ∙ 두부김치 ∙ 떡구이,∙2022.10.7. 영상 업로드,47,또간집,서울특별시 마포구 창전동,...,89811,13123910,53355,naver_13123910,마포구,89811,02-334-0118,023340118,산울림,100
87669,946,도문집,NaN,강원 속초시 금호동,033-633-5150,칼국수 ∙ 김치만두,∙2023.3.3 영상 업로드,78,또간집,강원특별자치도 속초시 금호동,...,287500,15007966,91019,naver_15007966,속초시,287500,033-633-5150,0336335150,원조도문집칼국수,100
89314,972,가양칼국수,풍자의 또갈집! 국물이 끝내주는 샤부샤부!,서울 영등포구 여의도동,02-784-0409,버섯매운탕,∙2023.6.9 영상 업로드,104,또간집,서울특별시 영등포구 여의도동,...,28557,11624237,13129,naver_11624237,영등포구,28557,02-784-0409,027840409,가양칼국수버섯매운탕,100
89315,990,심야식당 하리,오마카세 이기는 숙성 모듬회 맛집!,서울 광진구 화양동,070-7543-5786,사시미모리아와세 ∙ 후토마키,∙2023.9.1 영상 업로드,122,또간집,서울특별시 광진구 화양동,...,96330,1788964214,925518,naver_1788964214,광진구,96330,070-7543-5786,07075435786,하리,100
91642,1037,아리조나막창,생으로 구워먹는 고소한 대구 막창,대구 수성구 두산동,053-782-9323,생막창,∙2024.4.12. 영상 업로드,169,또간집,대구광역시 수성구 두산동,...,559312,11731271,504816,naver_11731271,수성구,559312,053-782-9323,0537829323,대구아리조나막창수성못본점,100

In [230]:
merge4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 0 to 91642
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        34 non-null     int64
 1   상점명               34 non-null     object
 2   content           25 non-null     object
 3   주소                34 non-null     object
 4   전화번호              31 non-null     object
 5   메인메뉴              34 non-null     object
 6   방송날짜              34 non-null     object
 7   방송회차              34 non-null     int64
 8   프로그램명             34 non-null     object
 9   address_jibun     34 non-null     object
 10  address_road      3 non-null      object
 11  latitude          31 non-null     object
 12  longitude         31 non-null     object
 13  AREA1             31 non-null     object
 14  AREA2             31 non-null     object
 15  AREA3             31 non-null     object
 16  store_id          34 non-null     int64
 17  naver_id          34 non-null     int64
 18  RSTR_ID           34 non-null     int64
 19  business_7        34 non-null     object
 20  AREA_NM_2         31 non-null     object
 21  id                34 non-null     int64
 22  telephone         31 non-null     object
 23  telephone_plain   31 non-null     object
 24  name              34 non-null     object
 25  similarity_ratio  34 non-null     int64
dtypes: int64(7), object(19)
memory usage: 7.2+ KB

In [271]:
store_rstr.columns

Index(['store_id', 'naver_id', 'RSTR_ID', 'business_7', 'AREA_NM_2'], dtype='object')

In [281]:
merge4_2.columns

Index(['Unnamed: 0', '상점명', 'content', '주소', '전화번호', '메인메뉴', '방송날짜', '방송회차',
       '프로그램명', 'address_jibun', 'address_road', 'latitude', 'longitude',
       'AREA1', 'AREA2', 'AREA3', 'ID', 'BSNS_LCNC_NO', 'SOURCE_ID',
       'FOODSAFETY_ID_NEW', 'SOURCE', 'RSTR_NM', 'AREA_NM_1', 'AREA_NM_2',
       'AREA_NM_3', 'RSTR_RDNMADR', 'RSTR_LNNO_ADRES', 'RSTR_ID', 'store_id'],
      dtype='object')

In [274]:
merge4_2 = merge1[merge1['ID'].notnull()]
merge4_2 = pd.merge(merge4_2,store_rstr[['RSTR_ID','store_id']], left_on='ID', right_on='RSTR_ID')

In [138]:
## 매칭안된 500개에 대해 전화번호로 연결

with dev_db_conn() as conn:
    cursor = conn.cursor()
    sql = f"""
SELECT T3.SRC_ID AS 'store_id',T4.FOODSAFETY_ID_NEW , T1.id AS 'naver_id', T2.RSTR_ID, CONCAT('naver_', T1.id) AS 'business_7'
FROM redtable_raw_2022.naver_restaurant T1
INNER JOIN redtable01.RSTR_CONN T2 ON T1.id = T2.SRC_ID
INNER JOIN redtable01.RSTR_CONN T3 ON T2.RSTR_ID = T3.RSTR_ID
INNER JOIN redtable01.RSTR T4 ON T4.ID = T2.RSTR_ID
WHERE T2.SRC = 'naver' AND T3.SRC = 'live_db';
    """
    cursor.execute(sql)
    store_rstr2 = cursor.fetchall()
store_rstr2 = pd.DataFrame(store_rstr2)
store_rstr2

        store_id  FOODSAFETY_ID_NEW    naver_id    RSTR_ID        business_7
0         199172           404339.0    16664019       1086    naver_16664019
1         129954                NaN  1117106356       1088  naver_1117106356
2         786516           703892.0  1845996048       1094  naver_1845996048
3         287609           291865.0    11782628       1096    naver_11782628
4         199137           510036.0  1456094039       1099  naver_1456094039
...          ...                ...         ...        ...               ...
561069   1190584          1165425.0  1368334876  300229974  naver_1368334876
561070   1190588          1165429.0  1555808990  300229978  naver_1555808990
561071   1190734          1165582.0  1290988160  300230130  naver_1290988160
561072   1190779          1165718.0  1146939043  300230176  naver_1146939043
561073   1190793          1165732.0  1234493232  300230190  naver_1234493232

[561074 rows x 5 columns]

In [ ]:
merge4 = pd.merge(merge4,store_rstr2[['RSTR_ID','FOODSAFETY_ID_NEW','store_id']],on=['RSTR_ID','store_id'])
merge4 = merge4.drop_duplicates(subset=['RSTR_ID','store_id','상점명','FOODSAFETY_ID_NEW'])
len(merge4)

In [288]:
merge4 = merge4[['RSTR_ID', 'FOODSAFETY_ID_NEW','프로그램명','방송회차','방송날짜','메인메뉴','store_id']]
merge4_2 = merge4_2[['ID','FOODSAFETY_ID_NEW','프로그램명','방송회차','방송날짜','메인메뉴','store_id']]

In [290]:
final = pd.concat([merge4, merge4_2],ignore_index=True,axis=0)
final

,RSTR_ID,FOODSAFETY_ID_NEW,프로그램명,방송회차,방송날짜,메인메뉴,store_id,ID
0,79048.0,236631.0,님아 그 시장을 가오,16,no date,쌈밥정식,30396,NaN
1,37278.0,831418.0,님아 그 시장을 가오,23,no date,생고기 ∙ 소고기 구이,194668,NaN
2,26277.0,398909.0,님아 그 시장을 가오,80,∙2024.3.28. 영상 업로드,고추야채통닭 ∙ 양념반후라이드반치킨,911047,NaN
3,457817.0,617480.0,최자로드,12,∙2024.4.25. 영상 업로드,반건조 민어찜 ∙ 갑오징어 구이 ∙ 딱돔 구이,43893,NaN
4,25041.0,531325.0,최자로드,34,∙2024.4.25. 영상 업로드,떡볶이,763007,NaN
...,...,...,...,...,...,...,...,...
543,NaN,635280.0,또간집,182,∙2024.6.7. 영상 업로드,닭갈비 ∙ 치즈사리 ∙ 우동사리 ∙ 막국수,300809,153861.0
544,NaN,635281.0,또간집,182,∙2024.6.7. 영상 업로드,닭갈비 ∙ 치즈사리 ∙ 우동사리 ∙ 막국수,15396,785030.0
545,NaN,825396.0,또간집,183,∙2024.6.7. 영상 업로드,닭갈비 ∙ 닭내장 ∙ 볶음밥,15701,481957.0
546,NaN,221717.0,또간집,184,∙2024.6.21. 영상 업로드,돌솥영양밥,36001,227923.0
547,NaN,784432.0,또간집,186,∙2024.6.21. 영상 업로드,가브리살,36922,53659.0

In [291]:
#final['FOODSAFETY_ID_NEW'].fillna(final['FOODSAFETY_ID_NEW_y'],inplace=True)
final['RSTR_ID'].fillna(final['ID'],inplace=True)
final.drop(columns={'ID'},inplace=True)
final
#final.to_excel("유튜브0626미완성본.xlsx")

,RSTR_ID,FOODSAFETY_ID_NEW,프로그램명,방송회차,방송날짜,메인메뉴,store_id
0,79048.0,236631.0,님아 그 시장을 가오,16,no date,쌈밥정식,30396
1,37278.0,831418.0,님아 그 시장을 가오,23,no date,생고기 ∙ 소고기 구이,194668
2,26277.0,398909.0,님아 그 시장을 가오,80,∙2024.3.28. 영상 업로드,고추야채통닭 ∙ 양념반후라이드반치킨,911047
3,457817.0,617480.0,최자로드,12,∙2024.4.25. 영상 업로드,반건조 민어찜 ∙ 갑오징어 구이 ∙ 딱돔 구이,43893
4,25041.0,531325.0,최자로드,34,∙2024.4.25. 영상 업로드,떡볶이,763007
...,...,...,...,...,...,...,...
543,153861.0,635280.0,또간집,182,∙2024.6.7. 영상 업로드,닭갈비 ∙ 치즈사리 ∙ 우동사리 ∙ 막국수,300809
544,785030.0,635281.0,또간집,182,∙2024.6.7. 영상 업로드,닭갈비 ∙ 치즈사리 ∙ 우동사리 ∙ 막국수,15396
545,481957.0,825396.0,또간집,183,∙2024.6.7. 영상 업로드,닭갈비 ∙ 닭내장 ∙ 볶음밥,15701
546,227923.0,221717.0,또간집,184,∙2024.6.21. 영상 업로드,돌솥영양밥,36001
547,53659.0,784432.0,또간집,186,∙2024.6.21. 영상 업로드,가브리살,36922

In [292]:
final['방송날짜'] = final['방송날짜'].apply(lambda x : x.replace("영상 업로드",""))
final['방송날짜'] = final['방송날짜'].apply(lambda x : x.replace("∙",""))
final['메인메뉴'] = final['메인메뉴'].apply(lambda x : x.replace("∙","/"))
final['방송날짜'] = final['방송날짜'].apply(lambda x: None if x == "no date" else x)
final

,RSTR_ID,FOODSAFETY_ID_NEW,프로그램명,방송회차,방송날짜,메인메뉴,store_id
0,79048.0,236631.0,님아 그 시장을 가오,16,None,쌈밥정식,30396
1,37278.0,831418.0,님아 그 시장을 가오,23,None,생고기 / 소고기 구이,194668
2,26277.0,398909.0,님아 그 시장을 가오,80,2024.3.28.,고추야채통닭 / 양념반후라이드반치킨,911047
3,457817.0,617480.0,최자로드,12,2024.4.25.,반건조 민어찜 / 갑오징어 구이 / 딱돔 구이,43893
4,25041.0,531325.0,최자로드,34,2024.4.25.,떡볶이,763007
...,...,...,...,...,...,...,...
543,153861.0,635280.0,또간집,182,2024.6.7.,닭갈비 / 치즈사리 / 우동사리 / 막국수,300809
544,785030.0,635281.0,또간집,182,2024.6.7.,닭갈비 / 치즈사리 / 우동사리 / 막국수,15396
545,481957.0,825396.0,또간집,183,2024.6.7.,닭갈비 / 닭내장 / 볶음밥,15701
546,227923.0,221717.0,또간집,184,2024.6.21.,돌솥영양밥,36001
547,53659.0,784432.0,또간집,186,2024.6.21.,가브리살,36922

In [299]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 548 entries, 0 to 547
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RSTR_ID            548 non-null    float64
 1   FOODSAFETY_ID_NEW  543 non-null    float64
 2   프로그램명              548 non-null    object
 3   방송회차               548 non-null    int64
 4   방송날짜               414 non-null    object
 5   메인메뉴               548 non-null    object
 6   store_id           548 non-null    int64
dtypes: float64(2), int64(2), object(3)
memory usage: 30.1+ KB

### DB 업데이트

In [300]:
i = 0
with live_db_conn() as conn:
    for _, row in final.iterrows():
        i += 1
        cursor = conn.cursor()

        #print(row)
        row.replace({pd.NA: None}, inplace=True)
        cursor.execute(f" SELECT * FROM redtable2021.store_media where admin_id = %s and title  = %s and menu  = %s and store_id  = %s and date  = %s ", (182,  row['프로그램명'], row['메인메뉴'], row['store_id'], row['방송날짜']))
        exis = cursor.fetchone()

        if exis:
            #print(exis)
            pass
        else :
            print(i)
            sql = """
            INSERT INTO redtable2021.store_media(store_id, admin_id , media, title, round, date, menu)
            VALUES (%s,%s,%s,%s,%s,%s,%s)"""
            val = (row['store_id'], 182, "YouTube", row['프로그램명'], row['방송회차'],row['방송날짜'],row['메인메뉴'])
            cursor.execute(sql, val)

1
2
16
17
18
19
20
21
22
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
77
89
91
92
109
110
113
116
121
127
129
132
163
168
172
178
185
193
194
197
202
206
208
218
225
250
257
277
281
283
287
293
294
303
309
310
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
413
423
427
438
439
447
454
459
473
482
485
489
495
519
521
522
523
543
544
545

In [267]:
with dev_db_conn() as conn:
    for _, row in final[140:].iterrows():
        cursor = conn.cursor()

        #print(row)
        row.replace({pd.NA: None}, inplace=True)
        cursor.execute(f" SELECT * FROM redtable01.RSTR_MDA where RSTR_ID = %s and BDCT_TM  = %s and BDCT_NM  = %s and BDCT_MENU_CN  = %s", (row['RSTR_ID'],  row['방송회차'], row['프로그램명'],row['메인메뉴']))
        exis = cursor.fetchone()

        if exis:
            print(exis)
            pass
        else :
            sql = """
            INSERT INTO redtable01.RSTR_MDA(RSTR_ID, FOODSAFETY_ID , CHNNL_NM, BDCT_NM, BDCT_TM, BDCT_DT, BDCT_MENU_CN)
            VALUES (%s,%s,%s,%s,%s,%s,%s)"""
            val = (row['RSTR_ID'], row['FOODSAFETY_ID_NEW'], "YouTube", row['프로그램명'], row['방송회차'],row['방송날짜'],row['메인메뉴'])
            cursor.execute(sql, val)
    print("업로드 완료")

{'ID': 24070, 'RSTR_ID': 723781, 'FOODSAFETY_ID': 112340, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '82', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '제육볶음 / 보리굴비 / 간장게장 / 임연수 구이', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24071, 'RSTR_ID': 349408, 'FOODSAFETY_ID': 748080, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '83', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '뭉텅찌개(돼지고기 김치찌개) / 칡비빔냉면', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24072, 'RSTR_ID': 90743, 'FOODSAFETY_ID': 642191, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '84', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '통추어탕 / 미꾸라지 튀김', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24073, 'RSTR_ID': 717330, 'FOODSAFETY_ID': 642192, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '84', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '통추어탕 / 미꾸라지 튀김', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24074, 'RSTR_ID': 91013, 'FOODSAFETY_ID': 481791, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '85', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '물곰탕 / 가자미 구이 / 가자미 조림', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24075, 'RSTR_ID': 299786, 'FOODSAFETY_ID': 519692, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '86', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '문어국밥 / 문어비빔국수', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24076, 'RSTR_ID': 788096, 'FOODSAFETY_ID': 519777, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '87', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '감자옹심이', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24077, 'RSTR_ID': 91343, 'FOODSAFETY_ID': 613865, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '88', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '섭국(자연산 홍합국) / 섭죽 / 섭무침', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24078, 'RSTR_ID': 197537, 'FOODSAFETY_ID': 783877, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '91', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '물닭갈비', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24079, 'RSTR_ID': 123510, 'FOODSAFETY_ID': 365029, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '92', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '까르니따스(돼지고기 타코) / 뻬스까도(생선 타코) / 뜨리빠(곱창 타코) / 부리토 / 까마로네스(새우볶음) / 칩 / 과카몰레', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24080, 'RSTR_ID': 580970, 'FOODSAFETY_ID': None, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '92', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '까르니따스(돼지고기 타코) / 뻬스까도(생선 타코) / 뜨리빠(곱창 타코) / 부리토 / 까마로네스(새우볶음) / 칩 / 과카몰레', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24081, 'RSTR_ID': 84788, 'FOODSAFETY_ID': 509288, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '93', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '닭고기 샤브샤브', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24082, 'RSTR_ID': 725513, 'FOODSAFETY_ID': 509289, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '93', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '닭고기 샤브샤브', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24083, 'RSTR_ID': 44595, 'FOODSAFETY_ID': 595344, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '94', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '돼지고기(가브리살) / 청국장 / 제육볶음', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24084, 'RSTR_ID': 711244, 'FOODSAFETY_ID': 384867, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '95', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '해물탕 / 갈치 조림', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24085, 'RSTR_ID': 225022, 'FOODSAFETY_ID': 731989, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '96', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '산채비빔밥 / 제육볶음 / 고등어구이 / 계란볶음', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24086, 'RSTR_ID': 4562, 'FOODSAFETY_ID': 331644, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '97', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '다금바리 회 / 다금바리 지리', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24087, 'RSTR_ID': 4566, 'FOODSAFETY_ID': 238902, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '98', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '꿩고기 구이 / 꿩메밀칼국수', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24088, 'RSTR_ID': 456535, 'FOODSAFETY_ID': 487165, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '99', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '소 내장탕', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 45), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24089, 'RSTR_ID': 300029726, 'FOODSAFETY_ID': 983534, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '99', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '소 내장탕', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24090, 'RSTR_ID': 17382, 'FOODSAFETY_ID': 867508, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '102', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '흑산도 홍어회 / 돼지고기 / 홍어탕', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24091, 'RSTR_ID': 19825, 'FOODSAFETY_ID': 311215, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '103', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '닭발 / 닭내장탕', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24092, 'RSTR_ID': 13189, 'FOODSAFETY_ID': 744164, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '104', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '감자국 / 제육볶음', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24093, 'RSTR_ID': 25461, 'FOODSAFETY_ID': 744158, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '104', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '감자국 / 제육볶음', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24094, 'RSTR_ID': 500536, 'FOODSAFETY_ID': 486600, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '105', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '산약초 오리백숙', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24095, 'RSTR_ID': 62631, 'FOODSAFETY_ID': 821678, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '107', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '짬뽕밥 / 탕수육', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24096, 'RSTR_ID': 392561, 'FOODSAFETY_ID': 681094, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '108', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '삼겹살 / 제육짜글이', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24097, 'RSTR_ID': 28409, 'FOODSAFETY_ID': 654387, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '109', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '김치찌개 / 고기추가 / 라면사리', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}
{'ID': 24098, 'RSTR_ID': 3948, 'FOODSAFETY_ID': 402120, 'CHNNL_NM': 'YouTube', 'BDCT_NM': '최자로드', 'BDCT_TM': '111', 'BDCT_DT': '2024.4.25. ', 'BDCT_MENU_CN': '물막국수 / 편육 / 치악산막걸리', 'DB_CREATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'DB_UPDATED_AT': datetime.datetime(2024, 6, 27, 2, 46, 46), 'LIVEDB_UPDATE_AT': None, 'IS_LIVE_UPDATE': 0}

In [249]:
pd.reset_option('display.max_rows')

In [246]:
pd.set_option('display.max_rows', None)
#pd.reset_option('display.max_rows')

check= final['RSTR_ID'].value_counts()
idx = check[check >= 2].index
checkk = final[final['RSTR_ID'].isin(idx)]
checkk.sort_values(by=['RSTR_ID','프로그램명'])

Empty DataFrame
Columns: [RSTR_ID, FOODSAFETY_ID_NEW, 프로그램명, 방송회차, 방송날짜, 메인메뉴]
Index: []

In [191]:
a = pd.merge(df,final[['프로그램명','방송회차','RSTR_ID']],on=['프로그램명','방송회차'],how='left')
a.to_excel("rstrid중복체크.xlsx")

In [203]:
#final.loc[final['RSTR_ID'].isin(idx), 'RSTR_ID'] = np.nan
final.loc[final['RSTR_ID'].isin(idx), ['RSTR_ID','FOODSAFETY_ID_NEW']] = np.nan

In [205]:
final.sample(20)

,RSTR_ID,FOODSAFETY_ID_NEW,프로그램명,방송회차,방송날짜,메인메뉴
270,293734.0,485305.0,님아 그 시장을 가오,84,∙2024.4.18. 영상 업로드,홍소스즈토우 ∙ 꼴뚜기튀김 ∙ 바지락볶음 ∙ 홍소로우 ∙ 중국식새우튀김
730,587088.0,227733.0,또간집,1,∙2022.4.22. 영상 업로드,돈까스(등심카츠 ∙ 안심카츠)
310,69900.0,312929.0,최자로드,48,∙2024.4.25. 영상 업로드,산닭구이
228,925518.0,823041.0,또간집,122,∙2023.9.1 영상 업로드,사시미모리아와세 ∙ 후토마키
110,NaN,NaN,오사카에사는사람들TV,59,∙2024.4.25. 영상 업로드,미즈타키(일본식 닭고기 전골)
48,18313.0,452458.0,먹보스쭈엽이,184,∙2024.4.25. 영상 업로드,등심탕수육 ∙ 간짜장면 ∙ 우동 ∙ 짬뽕 ∙ 볶음밥 ∙ 오므라이스
578,3811.0,419772.0,홍석천이원일,50,∙2024.4.25. 영상 업로드,납작만두
199,441218.0,774585.0,고독한 미식가,130,∙2024.4.25. 영상 업로드,카스테라 팬케이크 ∙ 아이스 커피
468,392066.0,634794.0,먹보스쭈엽이,107,∙2024.4.25. 영상 업로드,회전초밥
380,275502.0,626554.0,먹보스쭈엽이,3,∙2024.4.25. 영상 업로드,소고기구이
548,73506.0,346019.0,홍석천이원일,25,∙2024.4.25. 영상 업로드,멸치회 무침 ∙ 멸치회 ∙ 돌멍게 ∙ 무늬오징어회 ∙ 해물라면
748,685094.0,648149.0,또간집,19,∙2022.6.17. 영상 업로드,치즈돈까스(feat.백김치)
237,84652.0,458918.0,또간집,180,∙2024.5.24. 영상 업로드,파불고기
274,311627.0,714380.0,최자로드,5,∙2024.4.25. 영상 업로드,양다리 구이 ∙ 양탕 ∙ 바지락 무침
649,562196.0,292059.0,먹을텐데,33,no date,양고기(양갈비) ∙ 향라육슬 ∙ 황진위미 ∙ 옥수수국수
762,579934.0,738470.0,또간집,35,∙2022.8.26. 영상 업로드,마라전골 ∙ 콘튀김
47,564870.0,429413.0,먹보스쭈엽이,183,∙2024.4.25. 영상 업로드,삼겹살 ∙ 순살프라이드치킨 ∙ 제육덮밥 ∙ 오징어덮밥 ∙ 청국장 ∙ 황도
376,74868.0,258220.0,최자로드,113,∙2024.4.25. 영상 업로드,무끄럽 쏨땀 ∙ 마크아텃(가지고기말이튀김) ∙ 꿍옵운센(새우당면) ∙ 호일라이남프릭...
688,86021.0,297844.0,먹을텐데,96,no date,후라이드 ∙ 치킨 떡볶이
606,54038.0,549300.0,먹을텐데,7,no date,감자탕 ∙ 제육볶음

In [304]:
with dev_db_conn() as conn:
    for _, row in df.iterrows():
        cursor = conn.cursor()

        #print(row)
        row.replace({pd.NA: None}, inplace=True)
        #cursor.execute(f" SELECT * FROM redtable01.RSTR_MDA where RSTR_ID = %s and BDCT_TM  = %s and BDCT_NM  = %s and BDCT_MENU_CN  = %s", (row['RSTR_ID'],  row['방송회차'], row['프로그램명'],row['메인메뉴']))
        #exis = cursor.fetchone()

        #if exis:
        #    print(exis)
        #    pass
        #else :
        sql = """
            INSERT INTO redtable_raw_2022.2024_mukbangmap_restaurant(media, title, round, date, menu, content, rstr_nm, address, phone)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)"""
        val = ("YouTube", row['프로그램명'], row['방송회차'],row['방송날짜'],row['메인메뉴'],row['content'],row['상점명'],row['주소'],row['전화번호'])
        cursor.execute(sql, val)